# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Cards')),
                ('desc', models.TextField(blank=True, null=True)),
                ('v_type', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=125)),
                ('likes', models.IntegerField(default=0)),
                ('uplaod_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='userss.UserProfile')),
            ],
            options={
                'verbose_name': 'Cards',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
