# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
