# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardss', '0002_auto_20170314_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.ImageField(upload_to='Cards', verbose_name='Banner Image for your blog'),
        ),
    ]
