# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:55
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cardss', '0003_auto_20170314_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='desc',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
