# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardss', '0004_auto_20170316_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='uplaod_date',
            new_name='upload_date',
        ),
    ]
