# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userss', '0001_initial'),
        ('cardss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank='True', null='True', verbose_name='your comment')),
                ('count', models.IntegerField(default=0)),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_on_card', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_comments', to='cardss.Cards')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='userss.UserProfile')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
